# Bag of Words

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd .DataFrame({'text':['This meal is vary tasty and affordable',
                           'This meal is not tasty and is affordable',
                           'This meal is delicious and cheap',
                           'Meal is tasty and meal tests good'],
                   'output':[1,0,1,1]})


In [3]:
df

text  output
0    This meal is vary tasty and affordable       1
1  This meal is not tasty and is affordable       0
2          This meal is delicious and cheap       1
3         Meal is tasty and meal tests good       1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    4 non-null      object
 1   output  4 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 192.0+ bytes


In [6]:
# Featue Extraction Method- Bag Of Words(Count Vectorization)
from sklearn.feature_extraction.text import CountVectorizer

C:\Users\achyu\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [7]:
cv = CountVectorizer(binary = False) # Frequency BOW
cv1 = CountVectorizer(binary = True) # Binary BOW

In [8]:
BOW = cv.fit_transform(df['text'])
BOW1 = cv1.fit_transform(df['text'])

In [9]:
print(cv.vocabulary_)

{'this': 10, 'meal': 6, 'is': 5, 'vary': 11, 'tasty': 8, 'and': 1, 'affordable': 0, 'not': 7, 'delicious': 3, 'cheap': 2, 'tests': 9, 'good': 4}


In [10]:
print(cv1.vocabulary_)

{'this': 10, 'meal': 6, 'is': 5, 'vary': 11, 'tasty': 8, 'and': 1, 'affordable': 0, 'not': 7, 'delicious': 3, 'cheap': 2, 'tests': 9, 'good': 4}


In [11]:
BOW
# Because total words are more but having less words in each row that why it creating sparse matrix 

<4x12 sparse matrix of type '<class 'numpy.int64'>'
	with 26 stored elements in Compressed Sparse Row format>

In [12]:
BOW.toarray()

array([[1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1],
       [1, 1, 0, 0, 0, 2, 1, 1, 1, 0, 1, 0],
       [0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 1, 1, 2, 0, 1, 1, 0, 0]], dtype=int64)

In [13]:
BOW1.toarray()

array([[1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1],
       [1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0],
       [0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0]], dtype=int64)

# N -Gram

In [14]:
# uni-gram is nothing but BOW - ngram_range = (1,1)
# Bi-gram (ngram_range = (2,2))

In [15]:
cv = CountVectorizer(ngram_range = (2,2), binary = True) # Frequency BOW

In [17]:
BOW = cv.fit_transform(df['text'])

In [18]:
print(cv.vocabulary_)

{'this meal': 15, 'meal is': 10, 'is vary': 9, 'vary tasty': 16, 'tasty and': 13, 'and affordable': 0, 'is not': 7, 'not tasty': 12, 'and is': 2, 'is affordable': 5, 'is delicious': 6, 'delicious and': 4, 'and cheap': 1, 'is tasty': 8, 'and meal': 3, 'meal tests': 11, 'tests good': 14}


In [21]:
cv1 = CountVectorizer(ngram_range = (1,2), binary = True) # combination of uni & Bigram

In [22]:
BOW1 = cv1.fit_transform(df['text'])

In [23]:
print(cv1.vocabulary_)
#here each word has number and each binary word has number

{'this': 25, 'meal': 16, 'is': 10, 'vary': 27, 'tasty': 21, 'and': 1, 'affordable': 0, 'this meal': 26, 'meal is': 17, 'is vary': 15, 'vary tasty': 28, 'tasty and': 22, 'and affordable': 2, 'not': 19, 'is not': 13, 'not tasty': 20, 'and is': 4, 'is affordable': 11, 'delicious': 7, 'cheap': 6, 'is delicious': 12, 'delicious and': 8, 'and cheap': 3, 'tests': 23, 'good': 9, 'is tasty': 14, 'and meal': 5, 'meal tests': 18, 'tests good': 24}


In [24]:
cv2 = CountVectorizer(ngram_range = (3,3), binary = True) # trigram

In [26]:
BOW2 = cv2.fit_transform(df['text'])

In [27]:
print(cv2.vocabulary_)

{'this meal is': 16, 'meal is vary': 10, 'is vary tasty': 6, 'vary tasty and': 17, 'tasty and affordable': 13, 'meal is not': 8, 'is not tasty': 4, 'not tasty and': 12, 'tasty and is': 14, 'and is affordable': 0, 'meal is delicious': 7, 'is delicious and': 3, 'delicious and cheap': 2, 'meal is tasty': 9, 'is tasty and': 5, 'tasty and meal': 15, 'and meal tests': 1, 'meal tests good': 11}


In [28]:
cv3 = CountVectorizer(ngram_range = (1,3), binary = True) # combination of all three

In [29]:
BOW3 = cv3.fit_transform(df['text'])

In [31]:
print(cv3.vocabulary_)

{'this': 41, 'meal': 23, 'is': 13, 'vary': 44, 'tasty': 34, 'and': 1, 'affordable': 0, 'this meal': 42, 'meal is': 24, 'is vary': 21, 'vary tasty': 45, 'tasty and': 35, 'and affordable': 2, 'this meal is': 43, 'meal is vary': 28, 'is vary tasty': 22, 'vary tasty and': 46, 'tasty and affordable': 36, 'not': 31, 'is not': 17, 'not tasty': 32, 'and is': 4, 'is affordable': 14, 'meal is not': 26, 'is not tasty': 18, 'not tasty and': 33, 'tasty and is': 37, 'and is affordable': 5, 'delicious': 9, 'cheap': 8, 'is delicious': 15, 'delicious and': 10, 'and cheap': 3, 'meal is delicious': 25, 'is delicious and': 16, 'delicious and cheap': 11, 'tests': 39, 'good': 12, 'is tasty': 19, 'and meal': 6, 'meal tests': 29, 'tests good': 40, 'meal is tasty': 27, 'is tasty and': 20, 'tasty and meal': 38, 'and meal tests': 7, 'meal tests good': 30}


In [32]:
BOW3.toarray()

array([[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 1],
       [1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
        0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0],
       [0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
        0, 0, 0]], dtype=int64)

In [33]:
pd.DataFrame(BOW3.toarray())

0   1   2   3   4   5   6   7   8   9   ...  37  38  39  40  41  42  43  \
0   1   1   1   0   0   0   0   0   0   0  ...   0   0   0   0   1   1   1   
1   1   1   0   0   1   1   0   0   0   0  ...   1   0   0   0   1   1   1   
2   0   1   0   1   0   0   0   0   1   1  ...   0   0   0   0   1   1   1   
3   0   1   0   0   0   0   1   1   0   0  ...   0   1   1   1   0   0   0   

   44  45  46  
0   1   1   1  
1   0   0   0  
2   0   0   0  
3   0   0   0  

[4 rows x 47 columns]

# TF - IDF

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [35]:
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

# this is only tf value

array([[0.43710551, 0.28931566, 0.        , 0.        , 0.        ,
        0.28931566, 0.28931566, 0.        , 0.35387458, 0.        ,
        0.35387458, 0.55441292],
       [0.39078548, 0.25865691, 0.        , 0.        , 0.        ,
        0.51731381, 0.25865691, 0.49566183, 0.31637453, 0.        ,
        0.31637453, 0.        ],
       [0.        , 0.29061394, 0.55690079, 0.55690079, 0.        ,
        0.29061394, 0.29061394, 0.        , 0.        , 0.        ,
        0.35546256, 0.        ],
       [0.        , 0.25958339, 0.        , 0.        , 0.49743724,
        0.25958339, 0.51916678, 0.        , 0.31750775, 0.49743724,
        0.        , 0.        ]])

In [37]:
print(tfidf.idf_)

# This is idf value

[1.51082562 1.         1.91629073 1.91629073 1.91629073 1.
 1.         1.91629073 1.22314355 1.91629073 1.22314355 1.91629073]


In [38]:
print(tfidf.get_feature_names_out())

['affordable' 'and' 'cheap' 'delicious' 'good' 'is' 'meal' 'not' 'tasty'
 'tests' 'this' 'vary']


In [39]:
# Applying n-gram on the tfidf, to check combination of words importance

In [40]:
tfidf = TfidfVectorizer(ngram_range = (1,2), binary = True)
tfidf.fit_transform(df['text']).toarray()

# this is only tf value

array([[0.29099792, 0.19260854, 0.36909396, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.19260854, 0.        , 0.        , 0.        , 0.        ,
        0.36909396, 0.19260854, 0.19260854, 0.        , 0.        ,
        0.        , 0.23558789, 0.23558789, 0.        , 0.        ,
        0.23558789, 0.23558789, 0.36909396, 0.36909396],
       [0.27299625, 0.18069342, 0.        , 0.        , 0.34626113,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.18069342, 0.34626113, 0.        , 0.34626113, 0.        ,
        0.        , 0.18069342, 0.18069342, 0.        , 0.34626113,
        0.34626113, 0.22101399, 0.22101399, 0.        , 0.        ,
        0.22101399, 0.22101399, 0.        , 0.        ],
       [0.        , 0.19860274, 0.        , 0.38058058, 0.        ,
        0.        , 0.38058058, 0.38058058, 0.38058058, 0.        ,
        0.19860274, 0.        , 0.38058058, 0.        , 0.        ,
  

In [41]:
print(tfidf.idf_)

# This is idf value

[1.51082562 1.         1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073 1.         1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073 1.         1.
 1.91629073 1.91629073 1.91629073 1.22314355 1.22314355 1.91629073
 1.91629073 1.22314355 1.22314355 1.91629073 1.91629073]


In [42]:
print(tfidf.get_feature_names_out())

['affordable' 'and' 'and affordable' 'and cheap' 'and is' 'and meal'
 'cheap' 'delicious' 'delicious and' 'good' 'is' 'is affordable'
 'is delicious' 'is not' 'is tasty' 'is vary' 'meal' 'meal is'
 'meal tests' 'not' 'not tasty' 'tasty' 'tasty and' 'tests' 'tests good'
 'this' 'this meal' 'vary' 'vary tasty']
