In [1]:
!pip install tensorflow_text

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 33.9 MB/s eta 0:00:00


In [2]:
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

In [3]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/3"

In [6]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [14]:
my_test = ['turn off your light','nice to meet you', 'I love Amma nanna anna']
text_preprocess = bert_preprocess_model(my_test)
text_preprocess.keys()

dict_keys(['input_mask', 'input_word_ids', 'input_type_ids'])

In [15]:
text_preprocess['input_type_ids']

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0

In [16]:
text_preprocess['input_word_ids']

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[  101,  2735,  2125,  2115,  2422,   102,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [ ]:
#101 - CLS token - as starting point
#102 - SEP token - as ending point

In [17]:
text_preprocess['input_mask']

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0

In [18]:
bert_model = hub.KerasLayer(encoder_url)

In [19]:
bert_result = bert_model(text_preprocess)

In [20]:
bert_result.keys()

dict_keys(['default', 'pooled_output', 'encoder_outputs', 'sequence_output'])

In [21]:
bert_result['default']
# 3 - sentence
#768 - bert base model length

<tf.Tensor: shape=(3, 768), dtype=float32, numpy=
array([[-0.93794596, -0.3204129 , -0.71590376, ..., -0.15335166,
        -0.7236935 ,  0.91708225],
       [-0.9151437 , -0.33769265, -0.32997796, ..., -0.27260193,
        -0.6857051 ,  0.9283448 ],
       [-0.88634646, -0.5127099 , -0.6439721 , ..., -0.34905112,
        -0.70260805,  0.912116  ]], dtype=float32)>

In [22]:
bert_result['sequence_output']

<tf.Tensor: shape=(3, 128, 768), dtype=float32, numpy=
array([[[-0.09479013,  0.34507287, -0.3461476 , ..., -0.31168923,
         -0.20191506,  0.19958632],
        [ 0.6735527 ,  0.1974334 ,  0.20752442, ..., -0.05503698,
         -0.21846071, -1.102461  ],
        [-0.28480273, -0.10346453, -0.29538357, ..., -0.12958232,
          0.4940308 , -0.05010235],
        ...,
        [ 0.35319188,  0.4622252 ,  0.45821887, ...,  0.13017753,
         -0.55591714,  0.08855156],
        [ 0.3004632 ,  0.4484887 ,  0.4657746 , ...,  0.07647607,
         -0.54536116,  0.04742362],
        [ 0.2925297 ,  0.41366357,  0.49874684, ...,  0.10523563,
         -0.5841932 ,  0.04041333]],

       [[ 0.07767205,  0.35863823,  0.14206295, ...,  0.01386192,
          0.21017273,  0.21966219],
        [ 0.2739254 , -0.09307075,  0.9069679 , ..., -0.20490491,
         -0.7874201 ,  0.6380344 ],
        [ 0.05126375,  0.10918806, -0.03899663, ..., -0.14166702,
         -0.13486539, -0.00274808],
        ...,

In [23]:
bert_result['pooled_output']

<tf.Tensor: shape=(3, 768), dtype=float32, numpy=
array([[-0.93794596, -0.3204129 , -0.71590376, ..., -0.15335166,
        -0.7236935 ,  0.91708225],
       [-0.9151437 , -0.33769265, -0.32997796, ..., -0.27260193,
        -0.6857051 ,  0.9283448 ],
       [-0.88634646, -0.5127099 , -0.6439721 , ..., -0.34905112,
        -0.70260805,  0.912116  ]], dtype=float32)>

In [24]:
 bert_result['encoder_outputs']

[<tf.Tensor: shape=(3, 128, 768), dtype=float32, numpy=
 array([[[ 1.23868361e-01,  5.15157878e-02, -7.50974342e-02, ...,
          -5.20934612e-02,  3.51240635e-02, -1.75303034e-02],
         [-3.12642455e-01, -4.49806675e-02,  1.40574932e-01, ...,
           5.07677317e-01,  2.16265500e-01, -1.76600003e+00],
         [-2.72732675e-01, -9.74208564e-02,  1.03812528e+00, ...,
          -7.58230090e-02,  7.15655029e-01, -2.25934982e-01],
         ...,
         [-3.68111134e-02, -1.22798443e-01,  5.77061892e-01, ...,
           2.57708549e-01, -3.56560379e-01, -6.11344315e-02],
         [-1.20892979e-01, -1.38749912e-01,  4.57589120e-01, ...,
           2.64469355e-01, -2.64082134e-01, -1.28106311e-01],
         [-1.63560137e-02, -8.69638771e-02,  4.63040948e-01, ...,
           5.82251251e-01, -5.81920683e-01, -2.12515116e-01]],
 
        [[ 9.67311636e-02,  5.99668846e-02, -2.51132250e-02, ...,
          -1.43103302e-04,  7.99752846e-02,  1.85275972e-02],
         [ 1.19450986e+00,  9.1

In [25]:
 len(bert_result['encoder_outputs'])
 # bert base model has 12 encoder that what it is showing(where as large model gives 24)

12