In [60]:
import numpy as np
import pandas as pd

df=pd.DataFrame({'Text':['Learnbay teaches Learnbay Learnbay Learnbay','Learnbay provides training',
                        'People write comments','Learnbay write comments'],
                 'Output' :[1,1,0,1]})

# Here 1-Means positvie review 0-Negative review

In [2]:
df

Text  Output
0  Learnbay teaches Learnbay Learnbay Learnbay       1
1                   Learnbay provides training       1
2                        People write comments       0
3                      Learnbay write comments       1

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Text    4 non-null      object
 1   Output  4 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 192.0+ bytes


In [3]:
#Bag of Words
from sklearn.feature_extraction.text import CountVectorizer
countvect=CountVectorizer()
#CountVectorizer is a ML concept


In [4]:
countvect=CountVectorizer(binary=True) #Binary BOW

In [19]:
countvect1=CountVectorizer(binary=False,max_features=3) 
#Count BOW
#max_features=3 -this will write max words per review to be considered

In [5]:
BagOfWord=countvect.fit_transform(df['Text'])

In [20]:
BagOfWord1=countvect1.fit_transform(df['Text'])

In [6]:
#vocab
print(countvect.vocabulary_)

{'learnbay': 1, 'teaches': 4, 'provides': 3, 'training': 5, 'people': 2, 'write': 6, 'comments': 0}


In [7]:
BagOfWord

<4x7 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [9]:
 BagOfWord=countvect.fit_transform(df['Text']).toarray()

In [21]:
 BagOfWord1=countvect1.fit_transform(df['Text']).toarray()

In [10]:
BagOfWord

array([[0, 1, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 1]], dtype=int64)

In [22]:
 BagOfWord1

array([[0, 4, 0],
       [0, 1, 0],
       [1, 0, 1],
       [1, 1, 1]], dtype=int64)

# n-gram

In [24]:
df

Text  Output
0  Learnbay teaches Learnbay Learnbay Learnbay       1
1                   Learnbay provides training       1
2                        People write comments       0
3                      Learnbay write comments       1

In [29]:
countvect=CountVectorizer(binary=True, ngram_range=(2,2))
BagOfWord=countvect.fit_transform(df['Text']).toarray()
print(countvect.vocabulary_)

{'learnbay teaches': 2, 'teaches learnbay': 6, 'learnbay learnbay': 0, 'learnbay provides': 1, 'provides training': 5, 'people write': 4, 'write comments': 7, 'learnbay write': 3}


In [30]:
BagOfWord

array([[1, 0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0, 1]], dtype=int64)

In [35]:
countvect=CountVectorizer(binary=True, ngram_range=(1,2))
BagOfWord2=countvect.fit_transform(df['Text']).toarray()
print(countvect.vocabulary_)

{'learnbay': 1, 'teaches': 10, 'learnbay teaches': 4, 'teaches learnbay': 11, 'learnbay learnbay': 2, 'provides': 8, 'training': 12, 'learnbay provides': 3, 'provides training': 9, 'people': 6, 'write': 13, 'comments': 0, 'people write': 7, 'write comments': 14, 'learnbay write': 5}


In [38]:
countvect=CountVectorizer(binary=True, ngram_range=(3,3))
BagOfWord3=countvect.fit_transform(df['Text']).toarray()
print(countvect.vocabulary_)

{'learnbay teaches learnbay': 2, 'teaches learnbay learnbay': 5, 'learnbay learnbay learnbay': 0, 'learnbay provides training': 1, 'people write comments': 4, 'learnbay write comments': 3}


In [40]:
BagOfWord2

array([[0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1]], dtype=int64)

# Stemming

In [48]:
import nltk
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [43]:
words=['run','runs','go','goes','history','historical','easily','fairly','walk','walks','walking']
words

['run',
 'runs',
 'go',
 'goes',
 'history',
 'historical',
 'easily',
 'fairly',
 'walk',
 'walks',
 'walking']

In [49]:
for word in words:
    print(word + " -------------> " + ps.stem(word)) 

run -------------> run
runs -------------> run
go -------------> go
goes -------------> goe
history -------------> histori
historical -------------> histor
easily -------------> easili
fairly -------------> fairli
walk -------------> walk
walks -------------> walk
walking -------------> walk


# Lemmitization

In [50]:
from nltk.stem import WordNetLemmatizer
lemm=WordNetLemmatizer()

In [51]:
for word in words:
    print(word + " -------------> " + lemm.lemmatize(word))

run -------------> run
runs -------------> run
go -------------> go
goes -------------> go
history -------------> history
historical -------------> historical
easily -------------> easily
fairly -------------> fairly
walk -------------> walk
walks -------------> walk
walking -------------> walking


In [52]:
editorial="Reports of drugs manufactured in India causing severe harm and dozens of patient deaths from across the world continue to trickle in, the latest being the deaths of two patients in Sri Lanka who were administered Indian-made anaesthetic drugs. Just last month, eye drops manufactured in India had caused eye infection in about 30 patients and blindness in 10 in Sri Lanka. While anaesthetic drugs made in India causing deaths are a first in the recent past, eye drops causing infections, blindness and even deaths were reported a few months ago in the United States, with the Atlanta-based Centers for Disease Control and Prevention (CDC) finding a highly drug-resistant bacteria in them. The series of adverse reports against drugs produced in India began last year when the World Health Organization (WHO) linked the deaths of at least 70 children in Gambia from acute kidney injury, to cough syrups. The culprit ingredient in the syrups was diethylene glycol and ethylene glycol — deadly chemicals used as a cheaper substitute for propylene glycol — that should never have been found in any medicine. Soon after the deaths in Gambia, cough syrups made in India and containing the two deadly chemicals killed 18 children in Uzbekistan in December 2022. In end-April this year, Indian-made cough syrup was again in the news when WHO flagged the contaminated drugs found in the Marshall Islands and Micronesia; the contamination was identified by the Australian regulator. Diethylene glycol-contaminated drugs have led to at least five incidents of poisoning in Chennai, Mumbai, Bihar, Gurugram and Jammu between 1972 and 2020."

In [53]:
editorial

'Reports of drugs manufactured in India causing severe harm and dozens of patient deaths from across the world continue to trickle in, the latest being the deaths of two patients in Sri Lanka who were administered Indian-made anaesthetic drugs. Just last month, eye drops manufactured in India had caused eye infection in about 30 patients and blindness in 10 in Sri Lanka. While anaesthetic drugs made in India causing deaths are a first in the recent past, eye drops causing infections, blindness and even deaths were reported a few months ago in the United States, with the Atlanta-based Centers for Disease Control and Prevention (CDC) finding a highly drug-resistant bacteria in them. The series of adverse reports against drugs produced in India began last year when the World Health Organization (WHO) linked the deaths of at least 70 children in Gambia from acute kidney injury, to cough syrups. The culprit ingredient in the syrups was diethylene glycol and ethylene glycol — deadly chemical

In [54]:
from nltk.corpus import stopwords

In [61]:
sentence=nltk.sent_tokenize(editorial)
sentence

['Reports of drugs manufactured in India causing severe harm and dozens of patient deaths from across the world continue to trickle in, the latest being the deaths of two patients in Sri Lanka who were administered Indian-made anaesthetic drugs.',
 'Just last month, eye drops manufactured in India had caused eye infection in about 30 patients and blindness in 10 in Sri Lanka.',
 'While anaesthetic drugs made in India causing deaths are a first in the recent past, eye drops causing infections, blindness and even deaths were reported a few months ago in the United States, with the Atlanta-based Centers for Disease Control and Prevention (CDC) finding a highly drug-resistant bacteria in them.',
 'The series of adverse reports against drugs produced in India began last year when the World Health Organization (WHO) linked the deaths of at least 70 children in Gambia from acute kidney injury, to cough syrups.',
 'The culprit ingredient in the syrups was diethylene glycol and ethylene glycol 

In [62]:
for i in range(len(sentence)):
    words=nltk.word_tokenize(sentence[i])
    words=[ps.stem(word) for word in words if word not in set(stopwords.words('english'))]
    sentence[i]=''.join(words)

In [68]:
sentence

['reportdrugmanufacturindiacausseverharmdozenpatientdeathacrossworldcontinutrickl,latestdeathtwopatientsrilankaadministindian-madanaesthetdrug.',
 'justlastmonth,eyedropmanufacturindiacauseyeinfect30patientblind10srilanka.',
 'whileanaesthetdrugmadeindiacausdeathfirstrecentpast,eyedropcausinfect,blindevendeathreportmonthagounitstate,atlanta-bascenterdiseascontrolprevent(cdc)findhighlidrug-resistbacteria.',
 'theseriadversreportdrugproducindiabeganlastyearworldhealthorgan()linkdeathleast70childrengambiaacutkidneyinjuri,coughsyrup.',
 'theculpritingredisyrupdiethylenglycolethylenglycol—deadlichemicusecheapersubstitutpropylenglycol—neverfoundmedicin.',
 'soondeathgambia,coughsyrupmadeindiacontaintwodeadlichemickill18childrenuzbekistandecemb2022.',
 'inend-aprilyear,indian-madcoughsyrupnewswhoflagcontamindrugfoundmarshalislandmicronesia;contaminidentifiaustralianregul.',
 'diethylenglycol-contamindrugledleastfiveincidpoisonchennai,mumbai,bihar,gurugramjammu19722020.']

In [66]:
for i in range(len(sentence)):
    words=nltk.word_tokenize(sentence[i])
    words=[lemm.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    sentence[i]=''.join(words)

In [69]:
sentence

['reportdrugmanufacturindiacausseverharmdozenpatientdeathacrossworldcontinutrickl,latestdeathtwopatientsrilankaadministindian-madanaesthetdrug.',
 'justlastmonth,eyedropmanufacturindiacauseyeinfect30patientblind10srilanka.',
 'whileanaesthetdrugmadeindiacausdeathfirstrecentpast,eyedropcausinfect,blindevendeathreportmonthagounitstate,atlanta-bascenterdiseascontrolprevent(cdc)findhighlidrug-resistbacteria.',
 'theseriadversreportdrugproducindiabeganlastyearworldhealthorgan()linkdeathleast70childrengambiaacutkidneyinjuri,coughsyrup.',
 'theculpritingredisyrupdiethylenglycolethylenglycol—deadlichemicusecheapersubstitutpropylenglycol—neverfoundmedicin.',
 'soondeathgambia,coughsyrupmadeindiacontaintwodeadlichemickill18childrenuzbekistandecemb2022.',
 'inend-aprilyear,indian-madcoughsyrupnewswhoflagcontamindrugfoundmarshalislandmicronesia;contaminidentifiaustralianregul.',
 'diethylenglycol-contamindrugledleastfiveincidpoisonchennai,mumbai,bihar,gurugramjammu19722020.']