# Data : we shall generate the OR data

x1 x2  --> y
0 0 --> 0
0 1 --> 1
1 0 --> 1
1 1 --> 1

In [1]:
import numpy as np
num_imputs = 4

In [3]:
input_array = np.array([[0,0],[0,1],[1,0],[1,1]])
input_array

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [4]:
# output data -- OR Function
output_array = np.array([0,1,1,1])
output_array

array([0, 1, 1, 1])

# Perceptron Model
## Importing libraries

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

# Model Definition

In [7]:
classifier = Sequential()
classifier.add(Dense(input_shape=(2,), units=1, activation='sigmoid'))
# bias term is added by default
classifier.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 3         
                                                                 
Total params: 3 (12.00 Byte)
Trainable params: 3 (12.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [8]:
classifier.compile(optimizer=SGD(learning_rate=0.5), loss='binary_crossentropy', metrics=['accuracy'])

In [9]:
classifier.fit(input_array, output_array, epochs=100)

Epoch 1/100
1/1 [==============================] - 4s 4s/step - loss: 0.7705 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 12ms/step - loss: 0.6654 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 13ms/step - loss: 0.5952 - accuracy: 0.7500
Epoch 4/100
1/1 [==============================] - 0s 11ms/step - loss: 0.5471 - accuracy: 0.7500
Epoch 5/100
1/1 [==============================] - 0s 14ms/step - loss: 0.5130 - accuracy: 0.7500
Epoch 6/100
1/1 [==============================] - 0s 11ms/step - loss: 0.4877 - accuracy: 0.7500
Epoch 7/100
1/1 [==============================] - 0s 11ms/step - loss: 0.4682 - accuracy: 0.7500
Epoch 8/100
1/1 [==============================] - 0s 10ms/step - loss: 0.4525 - accuracy: 0.7500
Epoch 9/100
1/1 [==============================] - 0s 13ms/step - loss: 0.4395 - accuracy: 0.7500
Epoch 10/100
1/1 [==============================] - 0s 11ms/step - loss: 0.4284 - accuracy: 0.7500
Epoch 11/100
1/1 [===

# Model prediction and validation

In [10]:
y_pred = classifier.predict(input_array)
y_pred = (y_pred > 0.5)
y_pred

1/1 [==============================] - 0s 97ms/step


array([[False],
       [ True],
       [ True],
       [ True]])

In [11]:
from sklearn.metrics import accuracy_score
print("Accuracy", accuracy_score(y_pred, output_array))

Accuracy 1.0


##### We see that after just few epochs the model's accuracy is 100% which means it is able to classify all the points correctly

# Perceptron Network for XOR data

### Data
#### we shall generate the XOR data
0 0 --> 0
0 1 -- > 1
1 0 -- > 1
1 1 -- > 0

In [12]:
input_array = np.array([[0,0],[0,1],[1,0],[1,1]])
input_array

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [13]:
# output data -- XOR Function
output_array = np.array([0,1,1,0])
output_array

array([0, 1, 1, 0])

In [14]:
classifier = Sequential()
classifier.add(Dense(input_shape=(2,), units=1, activation='sigmoid'))
# bias term is added by default
classifier.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 3 (12.00 Byte)
Trainable params: 3 (12.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
classifier.compile(optimizer=SGD(learning_rate=0.5), loss='binary_crossentropy', metrics=['accuracy'])

In [16]:
classifier.fit(input_array, output_array, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 387ms/step - loss: 0.7529 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 12ms/step - loss: 0.7486 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 11ms/step - loss: 0.7449 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 11ms/step - loss: 0.7415 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 12ms/step - loss: 0.7385 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 13ms/step - loss: 0.7357 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 13ms/step - loss: 0.7332 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 12ms/step - loss: 0.7308 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 11ms/step - loss: 0.7286 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 11ms/step - loss: 0.7265 - accuracy: 0.5000
Epoch 11/100
1/1 [

In [17]:
y_pred = classifier.predict(input_array)
y_pred = (y_pred > 0.5)
print("Accuracy", accuracy_score(y_pred, output_array))

1/1 [==============================] - 0s 40ms/step
Accuracy 0.5


In [18]:
y_pred

array([[False],
       [False],
       [ True],
       [ True]])

##### We see that after 100 epochs, the model's accuracy is 50% which means it is not able to classify all the points correctly. The model is not able to segregate the classes correctly (it's missclassifier)

# MultiLayer Perceptron (XOR Function)

In [19]:
input_array = np.array([[0,0],[0,1],[1,0],[1,1]])
output_array = np.array([0,1,1,0])

In [20]:
from IPython.utils.text import dedent
classifier = Sequential()
classifier.add(Dense(input_shape=(2,), units=10, activation='relu'))
classifier.add(Dense(units=1, activation='sigmoid'))
# bias term is added by default
classifier.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 10)                30        
                                                                 
 dense_3 (Dense)             (None, 1)                 11        
                                                                 
Total params: 41 (164.00 Byte)
Trainable params: 41 (164.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
classifier.compile(optimizer=SGD(learning_rate=0.5), loss='binary_crossentropy', metrics=['accuracy'])

In [22]:
classifier.fit(input_array, output_array, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 0.6820 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 16ms/step - loss: 0.6675 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 13ms/step - loss: 0.6540 - accuracy: 0.7500
Epoch 4/100
1/1 [==============================] - 0s 15ms/step - loss: 0.6416 - accuracy: 0.7500
Epoch 5/100
1/1 [==============================] - 0s 12ms/step - loss: 0.6325 - accuracy: 0.7500
Epoch 6/100
1/1 [==============================] - 0s 15ms/step - loss: 0.6233 - accuracy: 0.7500
Epoch 7/100
1/1 [==============================] - 0s 25ms/step - loss: 0.6152 - accuracy: 0.7500
Epoch 8/100
1/1 [==============================] - 0s 16ms/step - loss: 0.6049 - accuracy: 0.7500
Epoch 9/100
1/1 [==============================] - 0s 10ms/step - loss: 0.5957 - accuracy: 1.0000
Epoch 10/100
1/1 [==============================] - 0s 11ms/step - loss: 0.5866 - accuracy: 1.0000
Epoch 11/100
1/1 [===

In [23]:
y_pred = classifier.predict(input_array)
y_pred = (y_pred > 0.5)
print("Accuracy", accuracy_score(y_pred, output_array))

1/1 [==============================] - 0s 44ms/step
Accuracy 1.0
