In [1]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,SimpleRNN

In [2]:
# Simple RNN(Batch Size, TimeSteps & No of features)

model =Sequential()
model.add(SimpleRNN(3,input_shape = (4,5)))  # here 3=neurons, 4 =max words in a review, 5=total vocab size
model.add(Dense(1,activation ='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 3)                 27        
                                                                 
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [3]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

# 5,3 =>5*3 =15 ==>((4*3)+3)=15

(5, 3)


array([[ 0.7910959 , -0.45336902, -0.40964678],
       [ 0.48473507, -0.4800406 , -0.7132243 ],
       [-0.53792834,  0.32714492,  0.33840746],
       [ 0.6963069 ,  0.17137557, -0.23781472],
       [-0.56199133, -0.13798577, -0.32386672]], dtype=float32)

In [4]:
print(model.get_weights()[1].shape)
model.get_weights()[1]

# 3*3 =9

(3, 3)


array([[-0.9830742 , -0.1715124 , -0.0644099 ],
       [-0.18136355,  0.9608121 ,  0.20963627],
       [ 0.02593059,  0.21776961, -0.9756557 ]], dtype=float32)

In [5]:
print(model.get_weights()[2].shape)
model.get_weights()[2]

# 3

(3,)


array([0., 0., 0.], dtype=float32)

In [6]:
print(model.get_weights()[3].shape)
model.get_weights()[3]

# 3

(3, 1)


array([[ 1.0703202 ],
       [ 0.35570395],
       [-0.07235658]], dtype=float32)

In [7]:
print(model.get_weights()[4].shape)
model.get_weights()[4]
#1 =output
# total parameters =15+9+3+3+1 =31

(1,)


array([0.], dtype=float32)

# RNN Approach-1: Integer Encoding Method

In [8]:
import numpy as np
documents =['Good Morning','how are you','iam in hometown now','i dont know when i finish this course',
            'i should be good at programming','i have to enjoy the life','be patient',
            'you are looking good','krishna trance']

In [9]:
from keras.preprocessing.text import Tokenizer
tokenizer =Tokenizer(oov_token ='not_in_documents')

In [10]:
tokenizer.fit_on_texts(documents)

In [12]:
tokenizer.word_index

{'not_in_documents': 1,
 'i': 2,
 'good': 3,
 'are': 4,
 'you': 5,
 'be': 6,
 'morning': 7,
 'how': 8,
 'iam': 9,
 'in': 10,
 'hometown': 11,
 'now': 12,
 'dont': 13,
 'know': 14,
 'when': 15,
 'finish': 16,
 'this': 17,
 'course': 18,
 'should': 19,
 'at': 20,
 'programming': 21,
 'have': 22,
 'to': 23,
 'enjoy': 24,
 'the': 25,
 'life': 26,
 'patient': 27,
 'looking': 28,
 'krishna': 29,
 'trance': 30}

In [13]:
tokenizer.word_counts

OrderedDict([('good', 3),
             ('morning', 1),
             ('how', 1),
             ('are', 2),
             ('you', 2),
             ('iam', 1),
             ('in', 1),
             ('hometown', 1),
             ('now', 1),
             ('i', 4),
             ('dont', 1),
             ('know', 1),
             ('when', 1),
             ('finish', 1),
             ('this', 1),
             ('course', 1),
             ('should', 1),
             ('be', 2),
             ('at', 1),
             ('programming', 1),
             ('have', 1),
             ('to', 1),
             ('enjoy', 1),
             ('the', 1),
             ('life', 1),
             ('patient', 1),
             ('looking', 1),
             ('krishna', 1),
             ('trance', 1)])

In [14]:
tokenizer.document_count

9

In [15]:
documents

['Good Morning',
 'how are you',
 'iam in hometown now',
 'i dont know when i finish this course',
 'i should be good at programming',
 'i have to enjoy the life',
 'be patient',
 'you are looking good',
 'krishna trance']

In [16]:
sequences =tokenizer.texts_to_sequences(documents)
sequences

[[3, 7],
 [8, 4, 5],
 [9, 10, 11, 12],
 [2, 13, 14, 15, 2, 16, 17, 18],
 [2, 19, 6, 3, 20, 21],
 [2, 22, 23, 24, 25, 26],
 [6, 27],
 [5, 4, 28, 3],
 [29, 30]]

In [17]:
# Apply Zero Padding -pre or post

from keras.utils import pad_sequences
sequence =pad_sequences(sequences, padding ='post')
sequence1 =pad_sequences(sequences,padding ='pre')

In [18]:
sequence

array([[ 3,  7,  0,  0,  0,  0,  0,  0],
       [ 8,  4,  5,  0,  0,  0,  0,  0],
       [ 9, 10, 11, 12,  0,  0,  0,  0],
       [ 2, 13, 14, 15,  2, 16, 17, 18],
       [ 2, 19,  6,  3, 20, 21,  0,  0],
       [ 2, 22, 23, 24, 25, 26,  0,  0],
       [ 6, 27,  0,  0,  0,  0,  0,  0],
       [ 5,  4, 28,  3,  0,  0,  0,  0],
       [29, 30,  0,  0,  0,  0,  0,  0]], dtype=int32)

In [19]:
sequence1

array([[ 0,  0,  0,  0,  0,  0,  3,  7],
       [ 0,  0,  0,  0,  0,  8,  4,  5],
       [ 0,  0,  0,  0,  9, 10, 11, 12],
       [ 2, 13, 14, 15,  2, 16, 17, 18],
       [ 0,  0,  2, 19,  6,  3, 20, 21],
       [ 0,  0,  2, 22, 23, 24, 25, 26],
       [ 0,  0,  0,  0,  0,  0,  6, 27],
       [ 0,  0,  0,  0,  5,  4, 28,  3],
       [ 0,  0,  0,  0,  0,  0, 29, 30]], dtype=int32)

# Case Study: IMDB movie review sentiment classification dataset

In [20]:
from keras.datasets import imdb  # inbuilt dataset
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [21]:
(x_train,y_train),(x_test,y_test) = imdb.load_data()

17464789/17464789 [==============================] - 0s 0us/step


In [22]:
print(x_train.shape,y_train.shape),(x_test.shape,y_test.shape)

(25000,) (25000,)


(None, ((25000,), (25000,)))

In [23]:
x_train[2]

[1,
 14,
 47,
 8,
 30,
 31,
 7,
 4,
 249,
 108,
 7,
 4,
 5974,
 54,
 61,
 369,
 13,
 71,
 149,
 14,
 22,
 112,
 4,
 2401,
 311,
 12,
 16,
 3711,
 33,
 75,
 43,
 1829,
 296,
 4,
 86,
 320,
 35,
 534,
 19,
 263,
 4821,
 1301,
 4,
 1873,
 33,
 89,
 78,
 12,
 66,
 16,
 4,
 360,
 7,
 4,
 58,
 316,
 334,
 11,
 4,
 1716,
 43,
 645,
 662,
 8,
 257,
 85,
 1200,
 42,
 1228,
 2578,
 83,
 68,
 3912,
 15,
 36,
 165,
 1539,
 278,
 36,
 69,
 44076,
 780,
 8,
 106,
 14,
 6905,
 1338,
 18,
 6,
 22,
 12,
 215,
 28,
 610,
 40,
 6,
 87,
 326,
 23,
 2300,
 21,
 23,
 22,
 12,
 272,
 40,
 57,
 31,
 11,
 4,
 22,
 47,
 6,
 2307,
 51,
 9,
 170,
 23,
 595,
 116,
 595,
 1352,
 13,
 191,
 79,
 638,
 89,
 51428,
 14,
 9,
 8,
 106,
 607,
 624,
 35,
 534,
 6,
 227,
 7,
 129,
 113]

In [24]:
print(len(x_train[0]))
print(len(x_train[1]))
print(len(x_train[5]))

218
189
43


In [25]:
# padding required as we have different lengths or timesteps in each review
x_train =pad_sequences(x_train, padding ='post',maxlen =200) # we can use max_length to control no of words required
x_test = pad_sequences(x_test, padding ='post',maxlen =200)

In [26]:
print(len(x_train[0]))
print(len(x_train[1]))
print(len(x_train[5]))

200
200
200


# Simple RNN Model-Interger Encoding

In [27]:
model = Sequential()
model.add(SimpleRNN(32, input_shape =(200,1),return_sequences =False))
#return_sequences =False = many to one type rnn
model.add(Dense(1,activation ='sigmoid'))
model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [28]:
print((1*32+(32*32)+32))
print((32*1+1))

1088
33


In [29]:
model.compile(optimizer ='adam',loss ='binary_crossentropy',metrics =['accuracy'])
model.fit(x_train,y_train,epochs =10,batch_size =32,validation_data =(x_test,y_test))

Epoch 1/10
782/782 [==============================] - 107s 130ms/step - loss: 0.6976 - accuracy: 0.5048 - val_loss: 0.6991 - val_accuracy: 0.5009
Epoch 2/10
782/782 [==============================] - 100s 128ms/step - loss: 0.6942 - accuracy: 0.5053 - val_loss: 0.6950 - val_accuracy: 0.4996
Epoch 3/10
782/782 [==============================] - 100s 128ms/step - loss: 0.6938 - accuracy: 0.5046 - val_loss: 0.6942 - val_accuracy: 0.4985
Epoch 4/10
782/782 [==============================] - 109s 139ms/step - loss: 0.6935 - accuracy: 0.5022 - val_loss: 0.6947 - val_accuracy: 0.4962
Epoch 5/10
782/782 [==============================] - 109s 139ms/step - loss: 0.6936 - accuracy: 0.5051 - val_loss: 0.6939 - val_accuracy: 0.4995
Epoch 6/10
782/782 [==============================] - 109s 140ms/step - loss: 0.6935 - accuracy: 0.5033 - val_loss: 0.6946 - val_accuracy: 0.5023
Epoch 7/10
782/782 [==============================] - 109s 139ms/step - loss: 0.6933 - accuracy: 0.5048 - val_loss: 0.6950 -

In [30]:
# here i got pathetic accuracy because of 2 reasons
 #1.out of 2494 time steps, i considered max words as 200, so we don't get proper meaning by reducing the length
 #2. I used integer encoding as against embedding encoding

# Simple RNN Model-Interger Encoding-with max vocab

In [34]:
# padding required as we have different lengths or timesteps in each review
x_train1 =pad_sequences(x_train, padding ='post',maxlen =2494)
x_test1 = pad_sequences(x_test, padding ='post',maxlen =2494)

In [35]:
model = Sequential()
model.add(SimpleRNN(32, input_shape =(2494,1),return_sequences =False))
#return_sequences =False = many to one type rnn
model.add(Dense(1,activation ='sigmoid'))
model.summary()


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_3 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_3 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile(optimizer ='adam',loss ='binary_crossentropy',metrics =['accuracy'])
model.fit(x_train1,y_train,epochs =5,batch_size =32,validation_data =(x_test1,y_test))

Epoch 1/5
782/782 [==============================] - 1161s 1s/step - loss: 0.6942 - accuracy: 0.5013 - val_loss: 0.6935 - val_accuracy: 0.4962
Epoch 2/5
711/782 [==========================>...] - ETA: 1:31 - loss: 0.6936 - accuracy: 0.5063

#Approach 2-Embedding Method(Dense Representation)

In [37]:
model = Sequential()
model.add(Embedding(10000,2))
model.add(SimpleRNN(32,return_sequences =False))
model.add(Dense(1,activation ='sigmoid'))
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, None, 2)           20000     
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 32)                1120      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 21153 (82.63 KB)
Trainable params: 21153 (82.63 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [40]:
model.compile(optimizer ='adam',loss ='binary_crossentropy',metrics =['accuracy'])
model.fit(x_train,y_train,epochs =5,batch_size =32,validation_data =(x_test,y_test))

Epoch 1/5
782/782 [==============================] - 212s 270ms/step - loss: 0.6938 - accuracy: 0.5120 - val_loss: 0.6915 - val_accuracy: 0.5119
Epoch 2/5
782/782 [==============================] - 175s 224ms/step - loss: 0.6834 - accuracy: 0.5399 - val_loss: 0.6830 - val_accuracy: 0.5301
Epoch 3/5
782/782 [==============================] - 164s 210ms/step - loss: 0.6576 - accuracy: 0.5792 - val_loss: 0.6892 - val_accuracy: 0.5283
Epoch 4/5
782/782 [==============================] - 169s 217ms/step - loss: 0.6453 - accuracy: 0.5878 - val_loss: 0.7061 - val_accuracy: 0.5143
Epoch 5/5
782/782 [==============================] - 169s 216ms/step - loss: 0.6209 - accuracy: 0.6033 - val_loss: 0.7279 - val_accuracy: 0.5174


In [ ]:
# If we increase the epochs and embedding values we will get very good results